Minor typo fixes missed earlier
kushaldas/ircbot pull request #5
Opened 2017-06-20 06:45 UTC by jasonbraganza

2017-06-20 07:04 UTC, kushaldas commented
This one has merge conflicts.

2017-06-20 07:06 UTC, jasonbraganza commented
do I delete this and resubmit the changes?

2017-07-05 16:20 UTC, kushaldas requested changes

2017-07-05 16:20 UTC, kushaldas commented on docs/usage.rst
> +>>>>>>> 2aa6a76... Minor typo fixes missed earlier
I think this has many wrong lines :)

2017-07-05 16:20 UTC, kushaldas commented on docs/usage.rst
> +=======
Not sure about this one too.

2017-07-05 16:32 UTC, jasonbraganza commented
made changes and recommitted. Will that help?

2017-07-14 05:36 UTC, merged